apiVersion: v1
kind: Pod #오브젝트 명시
metadata: #이름, 라벨
  name: test
spec:
  containers:
    - name: test
      image: rapa.iptime.org:5000/nginx:latest

---

apiVersion: v1
kind: Service
metadata:
  name: test-svc
spec:
  selector:
    app: test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
